files_cert_name: '{{ files_hostnames | first }}'
files_hostnames:
    - 'files.{{ default_domain}}'
files_ipv6: ''

# Jirafeau settings
files_style: 'dark-courgette'
files_root: '/var/www/files'
files_var: ''
files_company: Jirafeau
files_contact: 'Abuse <abuse@{{ default_domain }}>'
files_title: File Transfer
files_crypt_enable: false
files_upload_passwords: []
files_upload_allow_ips: []
files_upload_passwordless_ips: []
#files_admin_password: 

php_version: php8.4
php_fpm: '{{ php_version }}-fpm'